language: node_js
node_js: 
  - lts/*

script:
  - node sync.js --cookie "${COOKIE}" --ua "${UA}"

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  target_branch: master
  local_dir: output
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable